spring.application.name=learningSpringBootApp

# MySQL Connection
spring.datasource.url=jdbc:mysql://localhost:3306/SpringBootPractise
spring.datasource.username=root
spring.datasource.password=Tushar123@

# JPA Settings
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true

server.servlet.context-path=/api


#//First create tables using JPA (Hibernate), then run SQL scripts like data.sql.?
spring_jpa.defer-datasource_initialization=true

#Always run SQL scripts (schema.sql, data.sql) on application startup.
spring.sql.init.mode=always

#Tells Spring Boot where your data.sql file is located.
spring.sql.data-location=classpath:data.sql






























